version: '2'

services:
  signalk:
    image: signalk/signalk-server:latest
    container_name: signalk
    ports:
      - "3000"      # Web interface (internal only)
      - "8375:8375"      # NMEA 0183 TCP input
      - "10110:10110"    # NMEA 0183 TCP output
      - "8443:8443"      # HTTPS
    volumes:
      - signalk-config:/home/node/.signalk  # Settings persistence
      - nmea-logs:/home/node/.signalk/logs  # Map logs directory to host
    environment:
      - NMEA0183PORT=10110
      - SIGNALK_NODE_VERSION=latest
    restart: unless-stopped
    # labels:
    #   io.balena.features.supervisor-api: '1'

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086"      # InfluxDB UI and API (internal only)
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-marine}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-signalk}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_REPORTING_DISABLED=true
    restart: unless-stopped
    # labels:
    #   io.balena.features.supervisor-api: '1'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001"      # Grafana UI (internal only)
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel
      - GF_SERVER_ROOT_URL=${GRAFANA_ROOT_URL:-/grafana/}
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    depends_on:
      - influxdb
    restart: unless-stopped
    # labels:
    #   io.balena.features.supervisor-api: '1'

  avnav:
    build:
      context: ./avnav
    container_name: avnav
    ports:
      - "8080"      # AVNav web interface (internal only)
      - "8081:8081"      # NMEA over TCP (input) 
      - "8082:8082"      # NMEA over TCP (output)
    volumes:
      - avnav-home:/home/avnav/avnav  # AVNav user settings
      - avnav-charts:/home/avnav/charts  # For charts
    environment:
      - TZ=UTC
    restart: unless-stopped
    privileged: true     # This can help with permission issues in Balena
    depends_on:
      - signalk
    # labels:
    #   io.balena.features.supervisor-api: '1'

    
  traefik:
      build:
        context: ./traefik
      container_name: "traefik"
      # command:
      #   - "--log.level=DEBUG"
      #   # - "--api.insecure=true"
      #   - "--providers.docker=true"
      #   - "--providers.docker.exposedbydefault=false"
      #   - "--entryPoints.web.address=:80"
      ports:
        - "80:80"
        # - "8080:8080"
      # volumes:
      #   - /var/run/balena-engine.sock:/var/run/docker.sock:ro

volumes:
  nmea-logs:
  signalk-config:
  influxdb-data:
  influxdb-config:
  grafana-data:
  avnav-home:
  avnav-charts:
  nginx-config:
  nginx-config-gen: