version: '3'

services:
  signalk:
    image: signalk/signalk-server:latest
    container_name: signalk
    ports:
      - "3000:3000"      # Web interface
      - "8375:8375"      # NMEA 0183 TCP input
      - "10110:10110"    # NMEA 0183 TCP output
      - "8443:8443"      # HTTPS
    volumes:
      - signalk-config:/home/node/.signalk  # Settings persistence
      - ./volumes/nmea-logs:/home/node/.signalk/logs  # Map logs directory to host
    environment:
      - NMEA0183PORT=10110
      - SIGNALK_NODE_VERSION=latest
    restart: unless-stopped
    networks:
      - marine-network

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"      # InfluxDB UI and API
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=yourpassword
      - DOCKER_INFLUXDB_INIT_ORG=marine
      - DOCKER_INFLUXDB_INIT_BUCKET=signalk
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=your-super-secret-auth-token
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_REPORTING_DISABLED=true
    restart: unless-stopped
    networks:
      - marine-network

  telegraf:
    image: telegraf:1.28
    container_name: telegraf
    volumes:
      - ./volumes/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - INFLUX_TOKEN=${LOCAL_INFLUXDB_TOKEN:-your-super-secret-auth-token}
      - CLOUD_INFLUXDB_TOKEN=${CLOUD_INFLUXDB_TOKEN:-your-cloud-token}
    depends_on:
      - influxdb
    restart: unless-stopped
    networks:
      - marine-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"      # Grafana UI (mapped to 3001 to avoid conflict with SignalK)
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=yourpassword
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel
    depends_on:
      - influxdb
    restart: unless-stopped
    networks:
      - marine-network

volumes:
  signalk-config:
  influxdb-data:
  influxdb-config:
  grafana-data:

networks:
  marine-network:
    driver: bridge
