version: '3'

services:
  signalk:
    image: signalk/signalk-server:latest
    container_name: signalk
    ports:
      - "3000:3000"      # Web interface
      - "8375:8375"      # NMEA 0183 TCP input
      - "10110:10110"    # NMEA 0183 TCP output
      - "8443:8443"      # HTTPS
    volumes:
      - ./volumes/signalk-config:/home/node/.signalk  # Settings persistence
      - ./volumes/nmea-logs:/home/node/.signalk/logs  # Map logs directory to host
    environment:
      - NMEA0183PORT=10110
      - SIGNALK_NODE_VERSION=latest
    restart: unless-stopped
    networks:
      - marine-network

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"      # InfluxDB UI and API
    volumes:
      - ./volumes/influxdb-data:/var/lib/influxdb2
      - ./volumes/influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-marine}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-signalk}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_REPORTING_DISABLED=true
    restart: unless-stopped
    networks:
      - marine-network

  telegraf:
    image: telegraf:1.28
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - INFLUX_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - CLOUD_INFLUXDB_TOKEN=${CLOUD_INFLUXDB_TOKEN:-}
    depends_on:
      - influxdb
    restart: on-failure:3
    networks:
      - marine-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"      # Grafana UI (mapped to 3001 to avoid conflict with SignalK)
    volumes:
      - ./volumes/grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel
    depends_on:
      - influxdb
    restart: unless-stopped
    networks:
      - marine-network

  avnav:
    build:
      context: ./avnav  # Directory containing the Dockerfile
      dockerfile: Dockerfile
    container_name: avnav
    ports:
      - "80:8080"      # AVNav web interface
      - "8081:8081"      # NMEA over TCP (input) 
      - "8082:8082"      # NMEA over TCP (output)
    volumes:
      # - ./avnav/avnav_server.xml:/home/avnav/.avnav/avnav_server.xml:ro  # Configuration file
      - ./volumes/avnav-home:/home/avnav/avnav  # AVNav user settings
      - ./volumes/avnav-charts:/home/avnav/charts  # For charts
    environment:
      - TZ=UTC
    restart: unless-stopped
    networks:
      - marine-network
    depends_on:
      - signalk

volumes:
  signalk-config:
  influxdb-data:
  influxdb-config:
  grafana-data:
  avnav-home:
  avnav-charts:

networks:
  marine-network:
    driver: bridge
